@startuml

title __CONDITION's Class Diagram__\n

  package sase.specification {
    package sase.specification.creators {
      package sase.specification.creators.condition {
        abstract class BasicConditionSpecificationSetCreator {
            + createConditionSpecifications()
            - createDisjunctionConditionSpecifications()
            - getTypeByName()
            - isDisjunction()
            - createIteratedConditionSpecifications()
            - createNegativeConditionSpecifications()
            - getPositiveNonIteratedEventTypes()
            {abstract} # createPositiveNonIteratedConditionSpecifications()
        }
      }
    }
  }
  

  package sase.specification {
    package sase.specification.creators {
      package sase.specification.creators.condition {
        class ConditionSpecificationCreatorFactory {
            {static} + createConditionSpecificationSetCreator()
            {static} + createConditionSpecificationCreator()
            {static} + createConditionSpecificationCreator()
        }
      }
    }
  }
  

  package sase.specification {
    package sase.specification.creators {
      package sase.specification.creators.condition {
        enum ConditionSpecificationCreatorTypes {
          NONE
          STOCK_CORRELATION
          STOCK_DELTA
        }
      }
    }
  }
  

  package sase.specification {
    package sase.specification.creators {
      package sase.specification.creators.condition {
        enum ConditionSpecificationSetCreatorTypes {
          NONE
          COUNTERS
          TRIPLES
        }
      }
    }
  }
  

  package sase.specification {
    package sase.specification.creators {
      package sase.specification.creators.condition {
        class CountersConditionSpecificationSetCreator {
            {static} - minNumberOfConditions : int
            # createPositiveNonIteratedConditionSpecifications()
            - getNumberOfConditions()
            - selectUnoccupiedEventNames()
            - getRandomEventName()
            - consistsOfEventNames()
        }
      }
    }
  }
  

  package sase.specification {
    package sase.specification.creators {
      package sase.specification.creators.condition {
        interface IConditionSpecificationCreator {
            {abstract} + createDoubleEventCondition()
            {abstract} + createIteratedEventCondition()
        }
      }
    }
  }
  

  package sase.specification {
    package sase.specification.creators {
      package sase.specification.creators.condition {
        interface IConditionSpecificationSetCreator {
            {abstract} + createConditionSpecifications()
        }
      }
    }
  }
  

  package sase.specification {
    package sase.specification.creators {
      package sase.specification.creators.condition {
        class TriplesConditionSpecificationSetCreator {
            # createPositiveNonIteratedConditionSpecifications()
            - extractEventTypeNames()
            - getTripletsWithoutCondition()
            - containsCondition()
        }
      }
    }
  }
  

  BasicConditionSpecificationSetCreator -up-|> IConditionSpecificationSetCreator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
