@startuml

title __LOCAL's Class Diagram__\n

  package sase.sase.multi {
    package sase.sase.multi.calculator {
      package sase.sase.multi.calculator.local {
        abstract class GlobalImprovementBasedLocalSearchMPTCalculator {
            # maxStepsSinceImprovement : int
            + GlobalImprovementBasedLocalSearchMPTCalculator()
            # executeLocalSearch()
            {abstract} # initializeLocalSearch()
            {abstract} # executeLocalSearchStep()
        }
      }
    }
  }
  

  package sase.sase.multi {
    package sase.sase.multi.calculator {
      package sase.sase.multi.calculator.local {
        class IterativeImprovementMPTCalculator {
            - maxSteps : int
            - maxNeighbors : int
            + IterativeImprovementMPTCalculator()
            # executeLocalSearch()
        }
      }
    }
  }
  

  package sase.sase.multi {
    package sase.sase.multi.calculator {
      package sase.sase.multi.calculator.local {
        abstract class LocalSearchMPTCalculator {
            # algoUnit : IAlgoUnit
            # neighborhoodType : NeighborhoodTypes
            # timeLimit : Long
            - multiSetParameter : int
            {static} + createLocallyOptimalState()
            + LocalSearchMPTCalculator()
            + calculateMultiPlan()
            + improveMultiPlan()
            + getAlgoUnit()
            {abstract} # executeLocalSearch()
        }
      }
    }
  }
  

  package sase.sase.multi {
    package sase.sase.multi.calculator {
      package sase.sase.multi.calculator.local {
        class SimulatedAnnealingMPTCalculator {
            - alpha : double
            - numOfNeighborsForTempInit : int
            - currentCost : double
            - currentTemperature : double
            - random : Random
            + SimulatedAnnealingMPTCalculator()
            # initializeLocalSearch()
            # executeLocalSearchStep()
            - calculateInitialTemperature()
        }
      }
    }
  }
  

  package sase.sase.multi {
    package sase.sase.multi.calculator {
      package sase.sase.multi.calculator.local {
        class TabuSearchMPTCalculator {
            - neighborsPerStep : int
            - memorySize : int
            - memory : List<MultiPlan>
            + TabuSearchMPTCalculator()
            # initializeLocalSearch()
            # executeLocalSearchStep()
        }
      }
    }
  }
  

  LocalSearchMPTCalculator -up-|> IMPTCalculator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
