package sase.pattern.creation;

public enum PatternTypes {
	OLD_SEQUENCE_STOCK_CORRELATION,
	OLD_CONJUNCTION_STOCK_CORRELATION,
	
	STOCK_PATTERN,
	
	TRAM_CONGESTION_PATTERN,
	
	SPEEDD_TRAFFIC_PATTERN,
	SPEEDD_CREDIT_CARD_FRAUD_PATTERN,
	
	SYNTHETIC_PATTERN,
	
	TRAFFIC_PATTERN,
}
