@startuml

title __SYNTHETIC's Class Diagram__\n

  package sase.sase.user.synthetic {
    class SyntheticCondition {
        {static} - currentID : int
        - id : int
        - selectivityProvider : ISyntheticSelectivityProvider
        {static} + reset()
        + SyntheticCondition()
        # verifyDoubleEvent()
        # getConditionKey()
        + getId()
        + setSelectivityProvider()
    }
  }
  

  package sase.sase.user.synthetic {
    class SyntheticConditionSpecification {
        - firstEventName : String
        - secondEventName : String
        + SyntheticConditionSpecification()
        + getFirstEventName()
        + getSecondEventName()
        + createConditions()
        + toString()
        + getShortDescription()
    }
  }
  

  package sase.sase.user.synthetic {
    class SyntheticEventTypesConverter {
        + SyntheticEventTypesConverter()
        + convertToKnownEventType()
    }
  }
  

  package sase.sase.user.synthetic {
    class SyntheticEventTypesManager {
        - numberOfEventTypes : int
        {static} - eventTypes : EventType[]
        + SyntheticEventTypesManager()
        + getEventLabel()
        + getEventTimestamp()
        + convertStringPayloadToObjectPayload()
        + getAverageEventSize()
        + getKnownEventTypes()
        + getKnownEventTypeNames()
        # actuallyInitializeTypes()
        # createNameToTypeHash()
        # createLongNameToShortNameHash()
        {static} + getEventTypes()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
