@startuml

title __NEIGHBORHOOD's Class Diagram__\n

  package sase.sase.multi {
    package sase.sase.multi.calculator {
      package sase.sase.multi.calculator.local {
        package sase.sase.multi.calculator.local.neighborhood {
          abstract class LocalSearchNeighborhood {
              # graph : MultiPatternGraph
              # algoUnit : IAlgoUnit
              # currentState : MultiPlan
              # timeLimit : Long
              {static} # getObjectAtIndexFromCollection()
              + LocalSearchNeighborhood()
              + setCurrentState()
              + getCurrentState()
              - satisfiesSLARequirements()
              + getNextNeighbor()
              + getNextNeighbor()
              - getNextNeighbor()
              {abstract} # actuallyGetNextNeighbor()
          }
        }
      }
    }
  }
  

  package sase.sase.multi {
    package sase.sase.multi.calculator {
      package sase.sase.multi.calculator.local {
        package sase.sase.multi.calculator.local.neighborhood {
          class MultiSetShareNeighborhood {
              - maxPatternNum : int
              + MultiSetShareNeighborhood()
              # actuallyGetNextNeighbor()
              - selectPatternsForSharing()
              - isValidPatternSelection()
          }
        }
      }
    }
  }
  

  package sase.sase.multi {
    package sase.sase.multi.calculator {
      package sase.sase.multi.calculator.local {
        package sase.sase.multi.calculator.local.neighborhood {
          class NeighborhoodFactory {
              {static} + createNeighborhood()
          }
        }
      }
    }
  }
  

  package sase.sase.multi {
    package sase.sase.multi.calculator {
      package sase.sase.multi.calculator.local {
        package sase.sase.multi.calculator.local.neighborhood {
          enum NeighborhoodTypes {
            STATE_SWAP
            PAIRWISE
            MULTI_SET
          }
        }
      }
    }
  }
  

  package sase.sase.multi {
    package sase.sase.multi.calculator {
      package sase.sase.multi.calculator.local {
        package sase.sase.multi.calculator.local.neighborhood {
          class PairwiseShareNeighborhood {
              + PairwiseShareNeighborhood()
              # actuallyGetNextNeighbor()
              - isValidPatternSelection()
              - attemptToGetNextNeighbor()
              - filterNonMaxSubsets()
              - getRandomElement()
              # getRandomSubset()
              # createMultiPlanWithNewPlans()
          }
        }
      }
    }
  }
  

  package sase.sase.multi {
    package sase.sase.multi.calculator {
      package sase.sase.multi.calculator.local {
        package sase.sase.multi.calculator.local.neighborhood {
          class StateSwapNeighborhood {
              + StateSwapNeighborhood()
              # actuallyGetNextNeighbor()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
