@startuml

title __SPECIFICATION's Class Diagram__\n

  package sase.sase.user.stocks {
    package sase.sase.user.stocks.sase.specification {
      class IterativeAverageStockCorrelationConditionSpecification {
          - triggeringEventName : String
          - iterativeEventName : String
          - averagingEventName : String
          - correlationLimit : double
          + IterativeAverageStockCorrelationConditionSpecification()
          + getTriggeringEventName()
          + getIterativeEventName()
          + getAveragingEventName()
          + getCorrelationLimit()
          + createConditions()
          + toString()
          + getShortDescription()
      }
    }
  }
  

  package sase.sase.user.stocks {
    package sase.sase.user.stocks.sase.specification {
      class IterativeValueCmpStockCorrelationConditionSpecification {
          - precedingEventName : String
          - iterativeEventName : String
          - succeedingEventName : String
          + IterativeValueCmpStockCorrelationConditionSpecification()
          + getPrecedingEventName()
          + getIterativeEventName()
          + getSucceedingEventName()
          + createConditions()
          + toString()
          + getShortDescription()
      }
    }
  }
  

  package sase.sase.user.stocks {
    package sase.sase.user.stocks.sase.specification {
      class StockCorrelationConditionSpecification {
          - correlationLimit : double
          + StockCorrelationConditionSpecification()
          + StockCorrelationConditionSpecification()
          + getCorrelationLimit()
          + toString()
          + getShortDescription()
          # createDoubleEventCondition()
      }
    }
  }
  

  package sase.sase.user.stocks {
    package sase.sase.user.stocks.sase.specification {
      class StockDeltaOrderingConditionSpecification {
          + StockDeltaOrderingConditionSpecification()
          + StockDeltaOrderingConditionSpecification()
          + toString()
          # createDoubleEventCondition()
      }
    }
  }
  

  package sase.sase.user.stocks {
    package sase.sase.user.stocks.sase.specification {
      class StockFirstValueCmpConditionSpecification {
          - operation : ComparisonOperation
          + StockFirstValueCmpConditionSpecification()
          + StockFirstValueCmpConditionSpecification()
          + getOperation()
          + toString()
          + getShortDescription()
          # createDoubleEventCondition()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
