@startuml

title __PRODUCERS's Class Diagram__\n

  package sase.input {
    package sase.input.producers {
      class FileBasedEventProducer {
          - fileEventStreamReader : FileEventStreamReader
          + FileBasedEventProducer()
          # createMoreEvents()
          # canCreateMoreEvents()
          + finish()
      }
    }
  }
  

  package sase.input {
    package sase.input.producers {
      class FileEventStreamReader {
          - inputFilesPaths : String[]
          - eventsPerRead : int
          - currentFileIndex : int
          - hasMoreEvents : boolean
          - reader : BufferedReader
          + FileEventStreamReader()
          - enumerateDirectories()
          - enumerateDirectory()
          - initializeReader()
          - switchInputFile()
          - parseLine()
          + getRawEvent()
          + hasMoreEvents()
          + finish()
      }
    }
  }
  

  package sase.input {
    package sase.input.producers {
      interface ISyntheticSelectivityProvider {
          {abstract} + getSelectivity()
          {abstract} + getConditionEvaluationDuration()
      }
    }
  }
  

  package sase.input {
    package sase.input.producers {
      class SyntheticEventProducer {
          - specification : SyntheticInputSpecification
          - currentTimestamp : long
          - numberOfSentEvents : long
          - currentArrivalRates : Double[]
          - indicesOfParticipatingTypes : List<Integer>
          - currentSelectivities : Double[]
          - previousSelectivities : Double[]
          - timeOfLastInputModification : Long
          - timeOfNextInputModification : Long
          + SyntheticEventProducer()
          - initializeArrivalRates()
          - initializeSelectivities()
          - initializeIndicesOfParticipatingTypes()
          - validateArrayBounds()
          - createEventsForType()
          - executeInputModification()
          - modifyArrivalRates()
          - isValidRateUpdateIndex()
          - modifySelectivities()
          - isValidSelectivityUpdateIndex()
          - calculateNextInputModificationTime()
          - actuallyCreateMoreEvents()
          # createMoreEvents()
          # canCreateMoreEvents()
          + finish()
          + getSelectivity()
          + getConditionEvaluationDuration()
      }
    }
  }
  

  SyntheticEventProducer -up-|> ISyntheticSelectivityProvider


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
