@startuml

title __ITERATION's Class Diagram__\n

  package sase.pattern {
    package sase.pattern.condition {
      package sase.pattern.condition.iteration {
        class AggregatedExternalCondition {
            - aggregator : VectorAggregator
            - condition : Condition
            + AggregatedExternalCondition()
            # verifyListOfEventsWithExternalEvent()
            # getConditionKey()
        }
      }
    }
  }
  

  package sase.pattern {
    package sase.pattern.condition {
      package sase.pattern.condition.iteration {
        class FirstValueExternalCondition {
            - nestedCondition : DoubleEventCondition
            + FirstValueExternalCondition()
            # verifyListOfEventsWithExternalEvent()
        }
      }
    }
  }
  

  package sase.pattern {
    package sase.pattern.condition {
      package sase.pattern.condition.iteration {
        abstract class IteratedEventExternalCondition {
            + IteratedEventExternalCondition()
            # verifyDoubleEvent()
            {abstract} # verifyListOfEventsWithExternalEvent()
        }
      }
    }
  }
  

  package sase.pattern {
    package sase.pattern.condition {
      package sase.pattern.condition.iteration {
        abstract class IteratedEventInternalCondition {
            {static} - defaultSelectivity : double
            + IteratedEventInternalCondition()
            # verifySingleEvent()
            {abstract} # verifyAggregatedEvent()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
