@startuml

title __EAGER's Class Diagram__\n

  package sase.pattern {
    package sase.pattern.condition {
      package sase.pattern.condition.iteration {
        package sase.pattern.condition.iteration.eager {
          abstract class IteratedIncrementalCondition {
              + IteratedIncrementalCondition()
              # verifyAggregatedEvent()
              {abstract} + verifyAdjacentEvents()
          }
        }
      }
    }
  }
  

  package sase.pattern {
    package sase.pattern.condition {
      package sase.pattern.condition.iteration {
        package sase.pattern.condition.iteration.eager {
          class IteratedIncrementalDoubleEventCondition {
              - nestedCondition : DoubleEventCondition
              + IteratedIncrementalDoubleEventCondition()
              + verifyAdjacentEvents()
              # getConditionKey()
          }
        }
      }
    }
  }
  

  package sase.pattern {
    package sase.pattern.condition {
      package sase.pattern.condition.iteration {
        package sase.pattern.condition.iteration.eager {
          class IterationTriggerCondition {
              - triggerCondition : DoubleEventCondition
              - triggerConditionVerificationCache : HashMap<Event, Boolean>
              + IterationTriggerCondition()
              # verifyListOfEventsWithExternalEvent()
              + enableCache()
              + disableCache()
              + isCacheEnabled()
              # getConditionKey()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
