@startuml

title __TRAMS's Class Diagram__\n

  package sase.sase.user.trams {
    class TramCongestionEventTypesConverter {
        + TramCongestionEventTypesConverter()
        - getEventTypeByLinesCount()
        - getEventTypeByPatternLength()
        + convertToKnownEventType()
    }
  }
  

  package sase.sase.user.trams {
    class TramCongestionIntersectionCondition {
        + TramCongestionIntersectionCondition()
        - getEventLineNumbers()
        # verifyDoubleEvent()
        + toString()
        # getConditionKey()
    }
  }
  

  package sase.sase.user.trams {
    class TramCongestionIntersectionConditionSpecification {
        - firstEventName : String
        - secondEventName : String
        + TramCongestionIntersectionConditionSpecification()
        + getFirstEventName()
        + getSecondEventName()
        + createConditions()
        + toString()
        + getShortDescription()
    }
  }
  

  package sase.sase.user.trams {
    class TramEventTypesManager {
        {static} + timestampAttributeName : String
        {static} + lineNumbersAttributeName : String
        {static} + timestampAttributeIndex : int
        {static} + lineNumbersAttributeIndex : int
        {static} + lineNumbersSeparator : String
        {static} + normalTrafficEventTypeName : String
        {static} + lightCongestionEventTypeName : String
        {static} + mediumCongestionEventTypeName : String
        {static} + severeCongestionEventTypeName : String
        {static} + heavyCongestionEventTypeName : String
        {static} + normalTrafficEventType : EventType
        {static} + lightCongestionEventType : EventType
        {static} + mediumCongestionEventType : EventType
        {static} + severeCongestionEventType : EventType
        {static} + heavyCongestionEventType : EventType
        + TramEventTypesManager()
        # createNameToTypeHash()
        # createLongNameToShortNameHash()
        # actuallyInitializeTypes()
        + getEventLabel()
        + getEventTimestamp()
        + convertStringPayloadToObjectPayload()
        + getAverageEventSize()
        + getKnownEventTypes()
        + getKnownEventTypeNames()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
