@startuml

title __TRAFFIC's Class Diagram__\n

  package sase.user.speedd.traffic {
    class TrafficEventTypesManager {
        {static} + vehicleIDAttributeName : String
        {static} + timestampAttributeName : String
        {static} + xCoordinateAttributeName : String
        {static} + yCoordinateAttributeName : String
        {static} + speedAttributeName : String
        {static} + sectionAttributeName : String
        {static} + vehicleIDAttributeIndex : int
        {static} + timestampAttributeIndex : int
        {static} + xCoordinateAttributeIndex : int
        {static} + yCoordinateAttributeIndex : int
        {static} + speedAttributeIndex : int
        {static} + sectionAttributeIndex : int
        {static} - maxAttributeIndex : int
        {static} + veryLowSpeedEventType : EventType
        {static} + lowSpeedEventType : EventType
        {static} + mediumSpeedEventType : EventType
        {static} + highSpeedEventType : EventType
        {static} + veryHighSpeedEventType : EventType
        {static} + veryLowSpeedEventTypeName : String
        {static} + lowSpeedEventTypeName : String
        {static} + mediumSpeedEventTypeName : String
        {static} + highSpeedEventTypeName : String
        {static} + veryHighSpeedEventTypeName : String
        + TrafficEventTypesManager()
        + getEventLabel()
        + getEventTimestamp()
        + convertStringPayloadToObjectPayload()
        + getAverageEventSize()
        + getKnownEventTypes()
        + getKnownEventTypeNames()
        # actuallyInitializeTypes()
        # createNameToTypeHash()
        # createLongNameToShortNameHash()
    }
  }
  

  package sase.user.speedd.traffic {
    class TrafficSameVehicleIDConditionSpecification {
        - firstEventName : String
        - secondEventName : String
        + TrafficSameVehicleIDConditionSpecification()
        + createConditions()
        + getShortDescription()
    }
  }
  

  package sase.user.speedd.traffic {
    class TrafficSimilarVehicleIDCondition {
        {static} - maxDiff : long
        + TrafficSimilarVehicleIDCondition()
        + TrafficSimilarVehicleIDCondition()
        # verifyDoubleEvent()
        # getConditionKey()
    }
  }
  

  package sase.user.speedd.traffic {
    class TrafficSpeedEventTypesConverter {
        {static} - veryHighSpeedThreshold : Double
        {static} - highSpeedThreshold : Double
        {static} - mediumSpeedThreshold : Double
        {static} - lowSpeedThreshold : Double
        + TrafficSpeedEventTypesConverter()
        - getEventTypeBySpeed()
        + convertToKnownEventType()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
