@startuml

title __INPUT's Class Diagram__\n

  package sase.sase.specification {
    package sase.sase.specification.sase.input {
      abstract class InputSpecification {
          + type : EventStreamModifierTypes
          + InputSpecification()
          + toString()
          {abstract} + getShortDescription()
          {abstract} + getLongDescription()
      }
    }
  }
  

  package sase.sase.specification {
    package sase.sase.specification.sase.input {
      class RarestTypeDuplicatorInputSpecification {
          + filteringFactor : int
          + duplicatingFactor : int
          + RarestTypeDuplicatorInputSpecification()
          + getShortDescription()
          + getLongDescription()
      }
    }
  }
  

  package sase.sase.specification {
    package sase.sase.specification.sase.input {
      class ShuffleEventTypesInputSpecification {
          + reShufflingPeriod : Integer
          + ShuffleEventTypesInputSpecification()
          + getShortDescription()
          + getLongDescription()
      }
    }
  }
  

  package sase.sase.specification {
    package sase.sase.specification.sase.input {
      class SyntheticInputSpecification {
          + numberOfEvents : long
          + numberOfEventTypes : int
          + minimalArrivalRate : double
          + maximalArrivalRate : double
          + minimalSelectivity : double
          + maximalSelectivity : double
          + conditionEvaluationDuration : long
          + averageArrivalRateChangeRange : double
          + varianceInArrivalRateChangeRange : double
          + averageSelectivityChangeRange : double
          + varianceInSelectivityChangeRange : double
          + averageTimeBetweenInputChanges : long
          + varianceInTimeBetweenInputChanges : long
          + numberOfSimultaneousInputChanges : int
          + SyntheticInputSpecification()
          + getShortDescription()
          + getLongDescription()
      }
    }
  }
  

  package sase.sase.specification {
    package sase.sase.specification.sase.input {
      class TrivialInputSpecification {
          + TrivialInputSpecification()
          + getShortDescription()
          + getLongDescription()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
