@startuml

title __CONDITION's Class Diagram__\n

  package sase.user.stocks {
    package sase.user.stocks.condition {
      class StockAverageCorrelationCondition {
          + StockAverageCorrelationCondition()
      }
    }
  }
  

  package sase.user.stocks {
    package sase.user.stocks.condition {
      class StockCorrelationCondition {
          - minCorrelation : double
          + StockCorrelationCondition()
          + StockCorrelationCondition()
          - getStockHistory()
          - getCompanyName()
          # verifyDoubleEvent()
          + toString()
          # getConditionKey()
      }
    }
  }
  

  package sase.user.stocks {
    package sase.user.stocks.condition {
      class StockCorrelationIterationTriggerCondition {
          + StockCorrelationIterationTriggerCondition()
      }
    }
  }
  

  package sase.user.stocks {
    package sase.user.stocks.condition {
      class StockDeltaOrderingCondition {
          + StockDeltaOrderingCondition()
          + StockDeltaOrderingCondition()
          - calculateDelta()
          # verifyDoubleEvent()
          + toString()
          + equals()
          + hashCode()
      }
    }
  }
  

  package sase.user.stocks {
    package sase.user.stocks.condition {
      class StockFirstValueCmpCondition {
          + StockFirstValueCmpCondition()
          - getStockFirstValue()
          # verifyDoubleEvent()
          + toString()
      }
    }
  }
  

  package sase.user.stocks {
    package sase.user.stocks.condition {
      enum ComparisonOperation {
        SMALLER
        EQUALS
        BIGGER
        ANY
      }
    }
  }
  

  package sase.user.stocks {
    package sase.user.stocks.condition {
      class StockRangeCondition {
          - minRange : double
          + StockRangeCondition()
          - getStockPricesRange()
          # verifySingleEvent()
          + toString()
          # getConditionKey()
      }
    }
  }
  

  package sase.user.stocks {
    package sase.user.stocks.condition {
      class StockSameCompanyCondition {
          + StockSameCompanyCondition()
      }
    }
  }
  

  package sase.user.stocks {
    package sase.user.stocks.condition {
      class StockValueCmpIterationTriggerCondition {
          + StockValueCmpIterationTriggerCondition()
      }
    }
  }
  

  StockFirstValueCmpCondition o-- ComparisonOperation : operation
  StockFirstValueCmpCondition +-down- ComparisonOperation


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
