@startuml

title __FRAUD's Class Diagram__\n

  package sase.sase.user.speedd.fraud {
    class CreditCardFraudEventTypesConverter {
        {static} - veryLargeSumThreshold : Double
        {static} - largeSumThreshold : Double
        {static} - mediumSumThreshold : Double
        {static} - smallSumThreshold : Double
        + CreditCardFraudEventTypesConverter()
        - getNoFraudEventTypeByTransactionSum()
        - convertFraudToNoFraudEventType()
        + convertToKnownEventType()
    }
  }
  

  package sase.sase.user.speedd.fraud {
    class CreditCardFraudEventTypesManager {
        {static} + timestampAttributeName : String
        {static} + creditCardIDAttributeName : String
        {static} + transactionSumAttributeName : String
        {static} + isFraudAttributeName : String
        {static} + timestampAttributeIndex : int
        {static} + creditCardIDAttributeIndex : int
        {static} + transactionSumAttributeIndex : int
        {static} + isFraudAttributeIndex : int
        {static} - maxAttributeIndex : int
        {static} + internalTimestampAttributeIndex : int
        {static} + internalCreditCardIDAttributeIndex : int
        {static} + internalTransactionSumAttributeIndex : int
        {static} + internalIsFraudAttributeIndex : int
        {static} + verySmallTransactionNoFraudEventType : EventType
        {static} + smallTransactionNoFraudEventType : EventType
        {static} + mediumTransactionNoFraudEventType : EventType
        {static} + largeTransactionNoFraudEventType : EventType
        {static} + veryLargeTransactionNoFraudEventType : EventType
        {static} + verySmallTransactionFraudEventType : EventType
        {static} + smallTransactionFraudEventType : EventType
        {static} + mediumTransactionFraudEventType : EventType
        {static} + largeTransactionFraudEventType : EventType
        {static} + veryLargeTransactionFraudEventType : EventType
        {static} + verySmallTransactionNoFraudEventTypeName : String
        {static} + smallTransactionNoFraudEventTypeName : String
        {static} + mediumTransactionNoFraudEventTypeName : String
        {static} + largeTransactionNoFraudEventTypeName : String
        {static} + veryLargeTransactionNoFraudEventTypeName : String
        {static} + verySmallTransactionFraudEventTypeName : String
        {static} + smallTransactionFraudEventTypeName : String
        {static} + mediumTransactionFraudEventTypeName : String
        {static} + largeTransactionFraudEventTypeName : String
        {static} + veryLargeTransactionFraudEventTypeName : String
        + CreditCardFraudEventTypesManager()
        + getEventLabel()
        + getEventTimestamp()
        + convertStringPayloadToObjectPayload()
        + getAverageEventSize()
        + getKnownEventTypes()
        + getKnownEventTypeNames()
        # actuallyInitializeTypes()
        # createNameToTypeHash()
        # createLongNameToShortNameHash()
    }
  }
  

  package sase.sase.user.speedd.fraud {
    class SameCreditCardIDCondition {
        + SameCreditCardIDCondition()
        + SameCreditCardIDCondition()
        # verifyDoubleEvent()
        # getConditionKey()
    }
  }
  

  package sase.sase.user.speedd.fraud {
    class SameCreditCardIDConditionSpecification {
        - firstEventName : String
        - secondEventName : String
        + SameCreditCardIDConditionSpecification()
        + createConditions()
        + getShortDescription()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
