package sase.input;

public enum EventTypesConverterTypes {
	STOCK_BY_INDUSTRY_MEGA_LARGE_COMPANY,
	STOCK_BY_REGION,
	STOCK_BY_COMPANY,
	
	TRAM_CONGESTION,
	
	SPEEDD_TRAFFIC,
	SPEEDD_CREDIT_CARD_FRAUD,
	
	SYNTHETIC,
	TRAFFIC_SPEED_VEHICLES_NUMBER,
}
